name: build noyan-beton
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: windows-latest
steps:
   - name: Checkout code
     uses: actions/checkout@v2

 - name: Setup Node.js
     uses: actions/setup-node@v2
     with:
       node-version: '18.x'
       cache: 'npm'

    - name: Build and Push the Created Docker Image to your Docker Repo
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: your-docker-username/myfrontend
        tags: latest
        registry: docker.parsicgroup.ir
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
